export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_ERROR = 'AUTH_ERROR'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOG_OUT = 'LOG_OUT'
export const GET_ERROR = 'GET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const DASHBOARD_USER = 'DASHBOARD_USER'
export const DELETE_USER = 'DELETE_USER'

// Education_Experience_Profile
export const ADD_EDUCATION = 'ADD_EDUCATION'
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const DELETE_EDUCATION = 'DELETE_EDUCATION'
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE'
export const GET_EDUCATION = 'GET_EDUCATION'
export const GET_EXPERIENCE = 'GET_EXPERIENCE'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const EDUCATION_LOADING = 'EDUCATION_LOADING'
export const EXPERIENCE_LOADING = 'EXPERIENCE_LOADING'
export const PROFILE_LOADING = 'PROFILE_LOADING'

// gitHub
export const GIT_USERNAME_REPO = 'GIT_USERNAME_REPO'
export const GIT_USERNAME = 'GIT_USERNAME'